apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-app
  template:
    metadata:
      labels:
        app: covid-app
    spec:
      containers:
      - name: covid-app-container
        image: aadya/covid-symptom-checker:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: covid-app-service
spec:
  type: NodePort
  selector:
    app: covid-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007