apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-app-service
spec:
  type: NodePort
  selector:
    app: covid-app
  ports:
    - protocol: TCP
      port: 80           # External port (optional, can be 5000 too)
      targetPort: 5000   # Container's exposed port
      nodePort: 30007    # Exposed port on the Minikube VM (must be in range 30000-32767)

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: covid-app-service
# spec:
#   type: NodePort
#   selector:
#     app: covid-app
#   ports:
#     - port: 80
#       targetPort: 5000
#       nodePort: 30007