push-to-dockerhub:
  needs: build-and-test
  runs-on: ubuntu-latest

  steps:
    name: Checkout code
    uses: actions/checkout@v3

    name: Set up QEMU
    uses: docker/setup-qemu-action@v2

    name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3

    name: Log in to Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

    name: Load Docker image from cache
    run: docker load -i covid19-symptoms-checker.tar

    name: Push Docker image to Docker Hub
    run: |
      docker tag local/covid19-symptoms-checker:latest ${{ secrets.DOCKERHUB_USERNAME }}/covid19-symptoms-checker:latest
      docker push ${{ secrets.DOCKERHUB_USERNAME }}/covid19-symptoms-checker:latest
