name: Python Streamlit App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pylint
      run: |
        pip install pylint
        pylint app.py ml_dl_predict.py train_models.py --disable=R,C

    - name: Run tests
      run: |
        pip install pytest
        pytest tests/

    - name: Check Streamlit app runs
      run: |
        streamlit run app.py & sleep 10
        curl -I http://localhost:8501
